export const constantDropdownOptions = {
  durationOptions: [
    { label: "3 months", value: 3 },
    { label: "6 months", value: 6 },
    { label: "12 months", value: 12 },
    { label: "18 months", value: 18 },
    { label: "24 months", value: 24 },
    { label: "30 months", value: 30 },
    { label: "36 months", value: 36 },
    { label: "42 months", value: 42 },
    { label: "48 months", value: 48 },
    { label: "54 months", value: 54 },
    { label: "60 months", value: 60 },
  ],
  incomeOptions: [
    { label: "Monthly", value: 1 },
    { label: "2 months", value: 2 },
    { label: "3 months", value: 3 },
    { label: "4 months", value: 4 },
    { label: "5 months", value: 5 },
    { label: "6 months", value: 6 },
    { label: "7 months", value: 7 },
    { label: "8 months", value: 8 },
    { label: "9 months", value: 9 },
    { label: "10 months", value: 10 },
    { label: "11 months", value: 11 },
    { label: "12 months", value: 12 },
  ],
  riskScoreOptions: [
    { label: "A", value: "A" },
    { label: "B", value: "B" },
    { label: "C", value: "C" },
    { label: "D", value: "D" },
  ],
  annualRevenueOptions: [
    { label: "0-300k", value: "0-300k" },
    { label: "300k-600k", value: "300k-600k" },
    { label: "1M-2M", value: "1M-2M" },
    { label: "2M-4M", value: "2M-4M" },
    { label: "4M-7.5M", value: "4M-7.5M" },
  ],
  opportunityStatusOptions: [
    { label: "Active", value: "active" },
    { label: "Inactive", value: "inactive" },
    { label: "Coming Soon", value: "comingsoon" },
    { label: "Completed", value: "completed" },
    { label: "Settled", value: "settled" },
    { label: "Defaulted", value: "defaulted" },
  ],
};

export const documentHeadings = {
  companyDocs: [
    "Commercial Registration",
    "Article Of Association",
    "VAT Registration Certificate",
    "Saudization Certificate",
    "GOSI Certificate",
    "Chamber Of Commerce Certificate",
    "Additional Documents",
    "Partners Agreement To Hire Authorized Person To Request Funding",
  ],
  financialDocs: [
    "Bank Statement For The Last 12 Months",
    "Financial Statements For The Last Fiscal Year",
    "Bank Account Identification Certificate",
  ],
  bankDocs: ["Bank Additional Documents"],
};