import { atom } from "recoil";

export const userProfileAtom = atom({
  key: "userProfileAtom",
  default: {
    accounts: {
      balance: "0",
      wallet_id: 0,
      personal_iban_number: 0,
      bank_id: "",
      dnaneer_account_no: "",
      dnaneer_iban:"",
    },
    institutional: {
      bank: "",
      registration_number: "",
      company_name: "",
      establishment_date: "",
      address: "",
      legal_structure: "",
      source_of_income: "",
      annual_revenue: "",
      investor_name: "",
      position: "",
      id_number: "",
      phone_number: "",
      cr_number: "",
      high_level_mission: 0,
      senior_position: 0,
      marriage_relationship: 0,
      date_of_birth: "",
      annual_investment_amount: "",
    },
    individual: {
      education: "",
      employee: "No",
      current_company: "",
      current_position: "",
      current_experience: "",
      average_income: "",
      net_worth: "",
      source_of_income: "",
      name: "",
      // plan_to_invest: "",
      high_level_mission: 0,
      senior_position: 0,
      marriage_relationship: 0,
      investment_objectives: "",
      investment_knowledge: "",
    },
    advisor_id: null,
    advisor: null,
    cr_number: "",
    company_endorsement: 0,
    dob: "",
    profile_image_url: null,
    id: 0,
    _id: 0,
    mode: "",
    address: "",
    iban: "",
    business_name: "",
    cr_expiry_date: "",
    legal_type: "",
    total_roi: "",
    unrealized_profit: "0",
    total_investment_amount: "0",
    total_investment: "0",
    total_net_roi: "",
    name: "",
    phone_number: "",
    saudi_id_number: "",
    position: "",
    user_id: "",
    email: "",
    national_id: "",
    user_type: 0,
    kyc_step: 0,
    balance: "0",
    nafath: { englishFirstName: "", englishLastName: "" },
  },
});

export const borrowerProfileAtom = atom({
  key: "borrowerProfileAtom",
  default: {
    id: 0,
    phone_number: "+",
    user_type: 3,
    name: "",
    email: "",
    national_id: null,
    dob: null,
    profile_image_url: null,
    kyc_step: 0,
    mode: "",
    is_admin: 0,
    created_at: "",
    updated_at: "",
    advisor_id: null,
    transid: null,
    nafath: null,
    requestid: null,
    status: 1,
    classification_id: null,
    wathq: {},
    borrower: {
      id: 0,
      user_id: 0,
      cr_number: "",
      business_name: "",
      business_activity: "",
      legal_type: "",
      capital: "",
      cr_expiry_date: null,
      address: "",
      name: "",
      saudi_id_number: "",
      position: "",
      phone_number: "",
      dob: "",
      company_endorsement: 0,
      seeking_amount: "",
      repayment_duration: "",
      existing_obligations: 0,
      created_at: "",
      updated_at: "Z",
      reject_note: null,
      high_level_mission: 0,
      senior_position: 0,
      marriage_relationship: 0,
      status: "",
      step: 0,
      bank: null,
    },
    accounts: {
      id: 0,
      user_id: 0,
      wallet_id: null,
      personal_iban_number: "",
      dnaneer_iban: null,
      bank_id: 0,
      balance: "",
      created_at: null,
      updated_at: null,
      name: "",
      logo: "",
      code: null,
      status: 0,
      dnaneer_account_no:null,
    },
    advisor: null,
    classification: null,
  },
});
